blog_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("", include("blogs.urls")),
    path("register/", views.register, name="register"),
    path("login/", views.login, name='login'),
    path("logout/", views.logout, name='logout'),
    path("dashboard/", include("dashboard.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("blogs/search/", views.search, name="search"),
    path("blogs/<slug:slug>/", views.blogs, name="blogs"),
    path("category/<uuid:category_id>/", views.posts_by_category, name="posts_by_category")
]

dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    
    # paths for categories
    path("categories/", views.categories, name="categories"),
    path("categories/add/", views.add_categories, name="add_categories"),
    path("categories/edit/<uuid:pk>/", views.edit_categories, name="edit_categories"),
    path("categories/delete/<uuid:pk>/", views.delete_categories, name="delete_categories"),
    
    # paths for posts
    path('posts/', views.posts, name="posts"),
    path('posts/add/', views.add_posts, name="add_posts"),
    path('post/edit/<uuid:pk>/', views.edit_posts, name="edit_posts"),
    path('post/delete/<uuid:pk>/', views.delete_posts, name="delete_posts"),
    
    # paths for users
    path('users/', views.users, name="users"),
    path('users/add/', views.add_users, name='add_users'),
    path('users/edit/<uuid:pk>/', views.edit_users, name='edit_users'),
    path('users/delete/<uuid:pk>/', views.delete_users, name='delete_users'),
]

blogs/models.py
import uuid
from django.conf import settings
from django.db import models
from django.db.models import Manager
from django.contrib.auth.models import AbstractUser


class TimeStampedModel(models.Model):
    objects = Manager
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        abstract = True


class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True)


class Category(TimeStampedModel):
    category_name = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.category_name


STATUS_CHOICES = (
    ("draft", "Draft"), 
    ("published", "Published")
)


class Blogs(TimeStampedModel):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    blog_image = models.ImageField(upload_to="uploads/%y/%m/%d")
    short_description = models.TextField(max_length=2000)
    blog_body = models.TextField(max_length=3000)
    status = models.CharField(max_length=100, choices=STATUS_CHOICES, default="draft")
    is_feacherd = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "blogs"

    def __str__(self):
        return self.title


class Comment(TimeStampedModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blogs, on_delete=models.CASCADE)
    comment = models.TextField(max_length=250)
    
    def __str__(self):
        return self.comment

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from blogs.models import Category, Blogs, User
from django.contrib.auth.forms import UserCreationForm


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blogs
        fields = (
            "title",
            "category",
            "blog_image",
            "short_description",
            "blog_body",
            "status",
            "is_feacherd"
        )


class AddUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "is_active",
            "is_staff",
            "is_superuser",
            "groups",
            "user_permissions"
        )


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "is_active",
            "is_staff",
            "is_superuser",
            "groups",
            "user_permissions"
        )

dashboard/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.template.defaultfilters import slugify
from django.contrib import messages
from blogs.models import Category, Blogs, User
from dashboard.forms import CategoryForm, BlogForm, AddUserForm, EditUserForm


@login_required(login_url="login")
def dashboard(request):
    category_counts = Category.objects.all().count()
    blogs_counts = Blogs.objects.all().count()

    context = {
        "category_counts": category_counts, 
        "blogs_counts": blogs_counts
    }

    return render(request, "dashboard/dashboard.html", context)


def categories(request):
    return render(request, "dashboard/categories.html")


def add_categories(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Category created successfully!")
            return redirect("categories")
        else:
            print('Errors: ', form.errors)
            messages.error(request, "Failed to create category. Please check the form.")

    form = CategoryForm()
    context = {
        "form": form
    }
    return render(request, "dashboard/add_categories.html", context)


def edit_categories(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == "POST":
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, "Category modified successfully!")
            return redirect("categories")
        else:
            print('Errors: ', form.errors)
            messages.error(request, "Failed to edit category. Please check the form.")

    form = CategoryForm(instance=category)
    context = {
        "form": form, 
        "category": category
    }
    return render(request, "dashboard/edit_categories.html", context)


def delete_categories(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.delete()
    return redirect("categories")
    # return render(request, 'dashboard/categories.html')


def posts(request):
    posts = Blogs.objects.all()
    context = {
        'posts': posts
    }
    return render(request, "dashboard/posts.html", context)


def add_posts(request):
    if request.method == "POST":
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.slug = slugify(form.cleaned_data['title'])
            post.save()
            messages.success(request, "Post created successfully!")
            return redirect("posts")
        else:
            error_messages = "\n".join([f"{field}: {', '.join(errors)}" for field, errors in form.errors.items()])
            print('Errors: ', error_messages)
            messages.error(request, "Failed to create post. Please check the form.")

    form = BlogForm()
    context = {
        "form": form
    }
    return render(request, "dashboard/add_posts.html", context)


def edit_posts(request, pk):
    post = get_object_or_404(Blogs, pk=pk)
    if request.method == "POST":
        form = BlogForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.slug = slugify(form.cleaned_data["title"])
            post.save()
            messages.success(request, "Post updated successfully!")
            return redirect("posts")
        else:
            messages.error(request, "Failed to update post. Please check the form.")

    form = BlogForm(instance=post)
    context = {
        "form": form,
        "post": post
    }
    return render(request, "dashboard/edit_posts.html", context)


def delete_posts(request, pk):
    post = get_object_or_404(Blogs, pk=pk)
    post.delete()
    return redirect("posts")


def users(request):
    users = User.objects.all()
    context = {
        'users': users
    }
    return render(request, 'dashboard/users.html', context)


def add_users(request):
    if request.method == "POST":
        form = AddUserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users')
    form = AddUserForm()
    context = {
        'form': form
    }
    return render(request, 'dashboard/add_users.html', context)


def edit_users(request, pk):
    user = get_object_or_404(User, pk=pk)
    if request.method == "POST":
        form = EditUserForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, "Edit user info successfully!")
            return redirect('users')
        else:
            messages.error(request, "Failed to edit user. Please check the form.")
    
    form = EditUserForm(instance=user)
    context = {
        'form': form,
        'user': user
    }
    return render(request, 'dashboard/edit_users.html', context)


def delete_users(request, pk):
    user = get_object_or_404(User, pk=pk)
    user.delete()
    return redirect("users")

templates/dashboard/add_categories.html
{% extends '../base/base.html' %}

{% block content %}

<div class="row">
    <!-- left sidebar -->
    {% include './leftsidebar.html' %}

    {% load crispy_forms_tags %}
    <!-- right sidebar -->
    <div class="col-md-9">
        <h3>Add Category</h3>

        <form action="" method="POST" style="width: 350px;">
            {% csrf_token %}
            {{ form | crispy }}

            <button type="submit" class="btn btn-warning">Submit</button>
            <a href="{% url 'categories' %}" class="btn btn-secondary ml-2">Cancel</a>
        </form>
    </div>
</div>

{% endblock %}

templates/dashboard/add_posts.html
{% extends '../base/base.html' %}

{% block content %}

<div class="row">
    <!-- left sidebar -->
    {% include './leftsidebar.html' %}

    {% load crispy_forms_tags %}
    <!-- right sidebar -->
    <div class="col-md-9">
        <h3>Add New Post</h3>

        <form action="" method="POST" style="width: 350px;" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}

            <button type="submit" class="btn btn-warning">Submit</button>
            <a href="{% url 'posts' %}" class="btn btn-secondary ml-2">Cancel</a>
        </form>
    </div>
</div>

{% endblock %}

templates/dashboard/add_users.html
{% extends '../base/base.html' %}

{% block content %}

<div class="row">
    <!-- left sidebar -->
    {% include './leftsidebar.html' %}

    {% load crispy_forms_tags %}
    <!-- right sidebar -->
    <div class="col-md-9">
        <h3>Add New User</h3>

        <form action="{% url 'add_users' %}" method="POST" style="width: 500px;" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}

            <button type="submit" class="btn btn-warning">Submit</button>
            <a href="{% url 'users' %}" class="btn btn-secondary ml-2">Cancel</a>
        </form>
    </div>
</div>

{% endblock %}

templates/dashboard/categories.html
{% extends '../base/base.html' %}

{% block content %}

<div class="row">
    <!-- left sidebar -->
    {% include './leftsidebar.html' %}

    <!-- right sidebar -->
    <div class="col-md-9">
        <h3>All Categories</h3>
        <a href="{% url 'add_categories' %}" class="btn btn-dark text-light float-right mb-2">Add New Category</a>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Category Name</th>
                    <th>Created At</th>
                    <th>Updated At</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for cat in categories %}
                <tr>
                    <th>{{ forloop.counter }}</th>
                    <td>{{ cat.category_name }}</td>
                    <td>{{ cat.created_at }}</td>
                    <td>{{ cat.updated_at }}</td>
                    <td>
                        <a href="{% url 'edit_categories' cat.id %}"><i class="fas fa-edit text-success"></i></a> &nbsp;&nbsp;
                        <a href="{% url 'delete_categories' cat.id %}"><i class="fas fa-trash text-danger"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/dashboard/dashboard.html
{% extends '../base/base.html' %}

{% block content %}

<div class="row">
    <!-- left sidebar -->
    {% include './leftsidebar.html' %}

    <!-- right sidebar -->
    {% include './rightsidebar.html' %}
</div>

{% endblock %}

templates/dashboard/edit_categories.html
{% extends '../base/base.html' %}

{% block content %}

<div class="row">
    <!-- left sidebar -->
    {% include './leftsidebar.html' %}

    {% load crispy_forms_tags %}
    <!-- right sidebar -->
    <div class="col-md-9">
        <h3>Edit Category</h3>

        <form action="{% url 'edit_categories' category.id %}" method="POST" style="width: 350px;">
            {% csrf_token %}
            {{ form | crispy }}

            <button type="submit" class="btn btn-warning mb-5">Submit</button>
        </form>
    </div>
</div>

{% endblock %}

templates/dashboard/edit_posts.html
{% extends '../base/base.html' %}

{% block content %}

<div class="row">
    <!-- left sidebar -->
    {% include './leftsidebar.html' %}

    {% load crispy_forms_tags %}
    <!-- right sidebar -->
    <div class="col-md-9">
        <h3>Edit Post</h3>

        <form action="{% url 'edit_posts' post.id %}" method="POST" style="width: 350px;">
            {% csrf_token %}
            {{ form | crispy }}

            <button type="submit" class="btn btn-warning">Submit</button>
            <a href="{% url 'posts' %}" class="btn btn-secondary ml-2">Cancel</a>
        </form>
    </div>
</div>

{% endblock %}

templates/dashboard/edit_users.html
{% extends '../base/base.html' %}

{% block content %}

<div class="row">
    <!-- left sidebar -->
    {% include './leftsidebar.html' %}

    {% load crispy_forms_tags %}
    <!-- right sidebar -->
    <div class="col-md-9">
        <h3>Edit User Information</h3>

        <form action="{% url 'edit_users' user.id %}" method="POST" style="width: 500px;" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}

            <button type="submit" class="btn btn-warning">Submit</button>
            <a href="{% url 'users' %}" class="btn btn-secondary ml-2">Cancel</a>
        </form>
    </div>
</div>

{% endblock %}

templates/dashboard/leftsidebar.html
<div class="col-md-3">
    <div class="nav flex-column nav-pills bg-light aria-orientation='vertical">
        <a href="{% url 'dashboard' %}"
            class="nav-link text-dark {% if '/dashboard/' == request.path %} bg-warning font-weight-bold {% endif %}">
            Dashboard
        </a>
        {% if perms.auth.view_user %}
        <a href="{% url 'users' %}"
            class="nav-link text-dark {% if '/users/' in request.path %} bg-warning font-weight-bold {% endif %}">
            Users
        </a>
        {% endif %}
        <a href="{% url 'categories' %}"
            class="nav-link text-dark {% if '/categories/' in request.path %} bg-warning font-weight-bold {% endif %}">
            Categories
        </a>
        <a href="{% url 'posts' %}"
            class="nav-link text-dark {% if '/posts/' in request.path %} bg-warning font-weight-bold {% endif %}">
            Posts
        </a>
        <a href="{% url 'logout' %}" class="nav-link text-dark">
            Logout
        </a>
    </div>
</div>

templates/dashboard/posts.html
{% extends '../base/base.html' %}

{% block content %}

<div class="row">
    <!-- left sidebar -->
    {% include './leftsidebar.html' %}

    <!-- right sidebar -->
    <div class="col-md-9">
        <h3>All Posts</h3>
        <a href="{% url 'add_posts' %}" class="btn btn-dark text-light float-right mb-2">Add New Post</a>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Author</th>
                    <th>Status</th>
                    <th>Feacherd</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                <tr>
                    <th>{{ forloop.counter }}</th>
                    <td>{{ post.title }}</td>
                    <td>{{ post.category }}</td>
                    <td>{{ post.author }}</td>
                    <td>{{ post.status }}</td>
                    <td>
                        {% if post.is_feacherd %}
                        <i class="fas fa-check text-success"></i>
                        {% else %}
                        <i class="fas fa-times text-danger"></i>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'edit_posts' post.id %}"><i class="fas fa-edit text-success"></i></a>
                        &nbsp;&nbsp;
                        <a href="{% url 'delete_posts' post.id %}"><i class="fas fa-trash text-danger"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/dashboard/rightsidebar.html
<div class="col-md-9">
    <div class="row">
        <div class="col">
            <div class="card border-default mb-3">
                <div class="card-header text-center font-weight-bold">
                    <h3 class="text-dark">All Categories</h3>
                </div>
                <div class="card-body text-dark">
                    <h5 class="cart-title text-center">{{ category_counts }}</h5>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card border-default mb-3">
                <div class="card-header text-center font-weight-bold">
                    <h3 class="text-dark">All Posts</h3>
                </div>
                <div class="card-body text-dark">
                    <h5 class="cart-title text-center">{{ blogs_counts }}</h5>
                </div>
            </div>
        </div>
    </div>
</div>

templates/dashboard/users.html
{% extends '../base/base.html' %}

{% block content %}

<div class="row">
    <!-- left sidebar -->
    {% include './leftsidebar.html' %}

    <!-- right sidebar -->
    <div class="col-md-9">
        <h3>All Users</h3>
        <a href="{% url 'add_users' %}" class="btn btn-dark text-light float-right mb-2">Add New User</a>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Full Name</th>
                    <th>Email</th>
                    <th>Active</th>
                    <th>Staff</th>
                    <th>Superuser</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <th>{{ forloop.counter }}</th>
                    <td>{{ user.first_name }} {{ user.last_name }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.is_active }}</td>
                    <td>
                        {% if user.is_staff %}
                        <i class="fas fa-check text-success"></i>
                        {% else %}
                        <i class="fas fa-times text-danger"></i>
                        {% endif %}
                    </td>
                    <td>
                        {% if user.is_superuser %}
                        <i class="fas fa-check text-success"></i>
                        {% else %}
                        <i class="fas fa-times text-danger"></i>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'edit_users' user.id %}"><i class="fas fa-edit text-success"></i></a>
                        &nbsp;&nbsp;
                        <a href="{% url 'delete_users' user.id %}"><i class="fas fa-trash text-danger"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}